### ISSUE TITLE
Link to documentation is outdated

### ISSUE THREAD

**Issue by 197g** [Chopinsky/thread_pool#2]
The meta data in `Cargo.toml` still points to `thread_pool`, which is somewhat confusing when clicking the direct links in `crates.io` search results :)

https://github.com/Chopinsky/thread_pool/blob/6c6304415c90fd6ff76e243230cc3355cb573b98/Cargo.toml#L7

**Comment by Chopinsky** [comment]
Thanks for the heads up! I certainly missed it. Will fix it now.

**Comment by Chopinsky** [comment]
The link is fixed in [c8f81e](https://github.com/Chopinsky/thread_pool/commit/c8f81e24e2b0e2c65fd8ef06229fe1395680b3fb) and pushed to crates.io.
